# Generated by Django 5.2.16 on 2026-07-22 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_company_name_profile_is_employer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('experience_required', models.CharField(choices=[('fresher', 'Fresher'), ('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5+', '5+ years')], max_length=20)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('skills_required', models.CharField(blank=True, help_text='Comma-separated skills', max_length=300)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
