# Generated by Django 5.2.16 on 2026-07-28 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscriptionplan_employersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='core.jobapplication')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employer', 'application')},
            },
        ),
    ]
