# Generated by Django 5.2.16 on 2026-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resumeunlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
