# Generated by Django 5.2.16 on 2026-07-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jobapplication_is_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
