# Generated by Django 5.2.16 on 2026-08-11 09:16

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF only, max 5MB', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF only, max 5MB', null=True, upload_to='profile_resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), core.models.validate_file_size]),
        ),
    ]
