# Generated by Django 5.2.16 on 2026-08-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerSignupOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(help_text='Already-hashed password, never stored in plain text', max_length=128)),
                ('otp_code', models.CharField(max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
