# Generated by Django 5.2.16 on 2026-08-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jobseekersignupotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
