# Generated by Django 5.2.16 on 2026-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_adminloginotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='job',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
