# Generated by Django 5.2.16 on 2026-09-01 06:17

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_job_is_approved_job_approval_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_experienced',
            field=models.BooleanField(default=False, help_text='False = Fresher, True = Experienced'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_bgv_access',
            field=models.BooleanField(default=False, help_text='Whether this plan lets employers view background verification status'),
        ),
        migrations.CreateModel(
            name='BackgroundVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='not_requested', max_length=20)),
                ('has_new_documents', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, help_text='Visible to admin/verification team only')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_seeker_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_verification', to='core.jobseekerprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('degree_marksheet', 'Degree/College Marksheet'), ('relieving_letter', 'Relieving Letter'), ('payslip', 'Payslip'), ('offer_letter', 'Previous Offer Letter'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(help_text='PDF or image, max 5MB', upload_to='verification_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.models.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='core.jobseekerprofile')),
            ],
        ),
    ]
