# Generated by Django 5.2.16 on 2026-09-02 04:59

import core.models
import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_jobseekerprofile_is_experienced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(help_text='PDF or image, max 5MB', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/devi sanjai/Desktop/work/job portal/protected_media')), upload_to='verification_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.models.validate_file_size]),
        ),
    ]
