# Generated by Django 5.2.16 on 2026-09-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_verifierprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('pan_card', 'PAN Card'), ('id_other', 'Other Government ID'), ('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('degree_marksheet', 'Degree/College Marksheet'), ('relieving_letter', 'Relieving Letter'), ('payslip', 'Payslip'), ('offer_letter', 'Previous Offer Letter'), ('address_proof', 'Address Proof (Utility Bill / Rental Agreement)'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='BackgroundVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('criminal_check_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('clear', 'Clear'), ('flagged', 'Record Found')], default='not_checked', max_length=20)),
                ('has_new_documents', models.BooleanField(default=False)),
                ('internal_notes', models.TextField(blank=True, help_text='Visible to admin/verification team only')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='core.jobapplication')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests_made', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
