# Generated by Django 5.2.16 on 2026-09-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_verificationdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='document_type',
            field=models.CharField(choices=[('pan_card', 'PAN Card'), ('id_other', 'Other Government ID'), ('10th_marksheet', '10th Marksheet'), ('12th_marksheet', '12th Marksheet'), ('degree_marksheet', 'Degree/College Marksheet'), ('relieving_letter', 'Relieving Letter'), ('payslip', 'Payslip'), ('offer_letter', 'Previous Offer Letter'), ('address_proof', 'Address Proof (Utility Bill / Rental Agreement)'), ('criminal_record_certificate', 'Police Clearance / Criminal Record Certificate'), ('other', 'Other')], max_length=30),
        ),
    ]
