# Generated by Django 5.2.16 on 2026-09-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_verificationdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundverificationrequest',
            name='additional_info_requested',
            field=models.TextField(blank=True, help_text='Last message sent to candidate requesting more documents'),
        ),
    ]
