# Generated by Django 5.2.16 on 2026-09-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_backgroundverificationrequest_additional_info_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundverificationrequest',
            name='employer_report',
            field=models.TextField(blank=True, help_text='Detailed explanation shown to the employer once completed'),
        ),
        migrations.AlterField(
            model_name='backgroundverificationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Requested'), ('in_progress', 'Under Process'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
    ]
