# Generated by Django 5.2.16 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_backgroundverificationrequest_employer_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('job_query', models.CharField(help_text='What the job seeker was looking for', max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Notified', 'Notified')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
