# Generated by Django 5.2.16 on 2026-09-09 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_jobalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVerificationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(help_text='Price in INR')),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('candidate_limit', models.PositiveIntegerField()),
                ('includes_criminal_address', models.BooleanField(default=False, help_text='Whether criminal record and address verification are included')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerBGVSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('candidates_verified_count', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.backgroundverificationplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bgv_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
