# Generated by Django 5.2.16 on 2026-09-08

from datetime import timedelta

import django.core.validators
from django.db import migrations, models


def populate_expires_at(apps, schema_editor):
    """Give every existing job an expiry date based on its posted date."""
    Job = apps.get_model('core', 'Job')
    for job in Job.objects.all():
        months = job.expiry_months or 2
        job.expires_at = job.posted_at + timedelta(days=months * 30)
        job.save(update_fields=['expires_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_jobalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_months',
            field=models.PositiveIntegerField(
                choices=[(2, '2 months'), (3, '3 months'), (6, '6 months'), (12, '12 months')],
                default=2,
                help_text='The posting is automatically hidden after this long (minimum 2 months).',
                validators=[django.core.validators.MinValueValidator(2)],
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='inactive_reason',
            field=models.CharField(
                blank=True,
                choices=[('', 'Active'), ('filled', 'Position Filled'), ('expired', 'Expired'), ('closed', 'Closed by Employer')],
                default='',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(populate_expires_at, migrations.RunPython.noop),
    ]
