# Generated by Django 5.2.16 on 2026-09-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_backgroundverificationplan_employerbgvsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_bgv_used_count',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime count of free background verifications used'),
        ),
    ]
