# Generated by Django 5.2.16 on 2026-09-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_job_auto_expiry'),
        ('core', '0033_profile_free_bgv_used_count'),
    ]

    operations = [
    ]
